const categories = [
  { id: 1, name: "Appetizers" },
  { id: 2, name: "Salads" },
  { id: 3, name: "Entrees" },
  { id: 4, name: "Desserts" },
  { id: 5, name: "Beverages" },
];

const menuItems = [
  {
    title: "Bruschetta",
    description: "Toasted bread topped with fresh tomatoes, basil, and garlic.",
    price: "$6.99",
    image: "/images/1",
    categoryId: 1,
  },
  {
    title: "Stuffed Mushrooms",
    description: "Mushrooms stuffed with a savory blend of cheese and herbs.",
    price: "$8.99",
    image: "/images/2",
    categoryId: 1,
  },
  {
    title: "Mozzarella Sticks",
    description: "Fried mozzarella served with marinara dipping sauce.",
    price: "$7.99",
    image: "/images/3",
    categoryId: 1,
  },
  {
    title: "Fried Calamari",
    description: "Crispy calamari served with lemon wedges and marinara.",
    price: "$12.99",
    image: "/images/4",
    categoryId: 1,
  },
  {
    title: "Garlic Bread",
    description: "Warm bread toasted with garlic butter.",
    price: "$4.99",
    image: "/images/5",
    categoryId: 1,
  },
  {
    title: "Chicken Wings",
    description: "Spicy wings served with blue cheese dressing.",
    price: "$10.99",
    image: "/images/6",
    categoryId: 1,
  },
  {
    title: "Spinach Artichoke Dip",
    description:
      "Creamy dip with spinach and artichokes served with tortilla chips.",
    price: "$9.99",
    image: "/images/7",
    categoryId: 1,
  },

  {
    title: "Caesar Salad",
    description: "Romaine lettuce, croutons, parmesan, and Caesar dressing.",
    price: "$8.99",
    image: "/images/8",
    categoryId: 2,
  },
  {
    title: "Greek Salad",
    description: "Fresh vegetables, olives, feta cheese, and Greek dressing.",
    price: "$9.99",
    image: "/images/9",
    categoryId: 2,
  },
  {
    title: "House Salad",
    description:
      "Mixed greens with tomatoes, cucumbers, and choice of dressing.",
    price: "$5.99",
    image: "/images/10",
    categoryId: 2,
  },
  {
    title: "Caprese Salad",
    description: "Tomatoes, fresh mozzarella, basil, and balsamic glaze.",
    price: "$7.99",
    image: "/images/11",
    categoryId: 2,
  },
  {
    title: "Cobb Salad",
    description: "Mixed greens with chicken, bacon, avocado, and blue cheese.",
    price: "$12.99",
    image: "/images/12",
    categoryId: 2,
  },
  {
    title: "Tuna Salad",
    description: "Fresh tuna with greens, onions, and vinaigrette.",
    price: "$11.99",
    image: "/images/13",
    categoryId: 2,
  },
  {
    title: "Grilled Chicken Salad",
    description: "Grilled chicken served on a bed of fresh greens.",
    price: "$10.99",
    image: "/images/14",
    categoryId: 2,
  },

  {
    title: "Spaghetti Bolognese",
    description: "Pasta topped with a rich meat sauce.",
    price: "$14.99",
    image: "/images/15",
    categoryId: 3,
  },
  {
    title: "Chicken Parmesan",
    description: "Breaded chicken breast with marinara and mozzarella.",
    price: "$16.99",
    image: "/images/16",
    categoryId: 3,
  },
  {
    title: "Grilled Salmon",
    description: "Perfectly grilled salmon with lemon butter.",
    price: "$19.99",
    image: "/images/17",
    categoryId: 3,
  },
  {
    title: "Vegetable Stir Fry",
    description: "A medley of fresh vegetables stir-fried in a savory sauce.",
    price: "$13.99",
    image: "/images/18",
    categoryId: 3,
  },
  {
    title: "Beef Tenderloin",
    description: "Juicy tenderloin served with mashed potatoes.",
    price: "$22.99",
    image: "/images/19",
    categoryId: 3,
  },
  {
    title: "Lamb Chops",
    description: "Grilled lamb chops with rosemary sauce.",
    price: "$24.99",
    image: "/images/20",
    categoryId: 3,
  },
  {
    title: "Chicken Alfredo",
    description: "Creamy pasta with grilled chicken and Alfredo sauce.",
    price: "$15.99",
    image: "/images/21",
    categoryId: 3,
  },

  {
    title: "Cheesecake",
    description: "Rich and creamy cheesecake topped with strawberry sauce.",
    price: "$6.99",
    image: "/images/22",
    categoryId: 4,
  },
  {
    title: "Tiramisu",
    description: "Classic Italian dessert with layers of coffee-soaked cake.",
    price: "$7.99",
    image: "/images/23",
    categoryId: 4,
  },
  {
    title: "Chocolate Lava Cake",
    description: "Warm chocolate cake with a molten center.",
    price: "$8.99",
    image: "/images/24",
    categoryId: 4,
  },
  {
    title: "Gelato",
    description: "Italian-style ice cream with a variety of flavors.",
    price: "$5.99",
    image: "/images/25",
    categoryId: 4,
  },
  {
    title: "Apple Pie",
    description: "Classic apple pie with a buttery crust.",
    price: "$4.99",
    image: "/images/26",
    categoryId: 4,
  },
  {
    title: "Crème Brûlée",
    description: "Creamy custard with a caramelized sugar top.",
    price: "$7.49",
    image: "/images/27",
    categoryId: 4,
  },
  {
    title: "Panna Cotta",
    description: "Vanilla-flavored Italian dessert served with berry compote.",
    price: "$6.49",
    image: "/images/28",
    categoryId: 4,
  },

  {
    title: "Coffee",
    description: "Freshly brewed coffee served hot.",
    price: "$2.99",
    image: "/images/29",
    categoryId: 5,
  },
  {
    title: "Iced Tea",
    description: "Refreshing iced tea with lemon.",
    price: "$2.49",
    image: "/images/30",
    categoryId: 5,
  },
  {
    title: "Lemonade",
    description: "Freshly squeezed lemonade.",
    price: "$3.49",
    image: "/images/31",
    categoryId: 5,
  },
  {
    title: "Soda",
    description: "Choose from a variety of sodas.",
    price: "$1.99",
    image: "/images/32",
    categoryId: 5,
  },
  {
    title: "Milkshake",
    description: "Thick and creamy milkshake in vanilla or chocolate.",
    price: "$4.99",
    image: "/images/33",
    categoryId: 5,
  },
  {
    title: "Wine",
    description: "Select from a fine range of red and white wines.",
    price: "$7.99",
    image: "/images/34",
    categoryId: 5,
  },
  {
    title: "Beer",
    description: "Variety of craft beers available.",
    price: "$5.49",
    image: "/images/35",
    categoryId: 5,
  },
];
