const categories = [
  { id: 1, name: "Appetizers" },
  { id: 2, name: "Salads" },
  { id: 3, name: "Entrees" },
  { id: 4, name: "Desserts" },
  { id: 5, name: "Beverages" },
];

const menuItems = [
  {
    id: 1,
    title: "Bruschetta",
    description: "Toasted bread topped with fresh tomatoes, basil, and garlic.",
    price: "$6.99",
    image: "/images/1.jpg",
    categoryId: 1,
  },
  {
    id: 2,
    title: "Stuffed Mushrooms",
    description: "Mushrooms stuffed with a savory blend of cheese and herbs.",
    price: "$8.99",
    image: "/images/2.jpg",
    categoryId: 1,
  },
  {
    id: 3,
    title: "Mozzarella Sticks",
    description: "Fried mozzarella served with marinara dipping sauce.",
    price: "$7.99",
    image: "/images/3.jpg",
    categoryId: 1,
  },
  {
    id: 4,
    title: "Fried Calamari",
    description: "Crispy calamari served with lemon wedges and marinara.",
    price: "$12.99",
    image: "/images/4.jpg",
    categoryId: 1,
  },
  {
    id: 5,
    title: "Garlic Bread",
    description: "Warm bread toasted with garlic butter.",
    price: "$4.99",
    image: "/images/5.jpg",
    categoryId: 1,
  },
  {
    id: 6,
    title: "Chicken Wings",
    description: "Spicy wings served with blue cheese dressing.",
    price: "$10.99",
    image: "/images/6.jpg",
    categoryId: 1,
  },
  {
    id: 7,
    title: "Spinach Artichoke Dip",
    description:
      "Creamy dip with spinach and artichokes served with tortilla chips.",
    price: "$9.99",
    image: "/images/7.jpg",
    categoryId: 1,
  },
  {
    id: 8,
    title: "Caesar Salad",
    description: "Romaine lettuce, croutons, parmesan, and Caesar dressing.",
    price: "$8.99",
    image: "/images/8.jpg",
    categoryId: 2,
  },
  {
    id: 9,
    title: "Greek Salad",
    description: "Fresh vegetables, olives, feta cheese, and Greek dressing.",
    price: "$9.99",
    image: "/images/9.jpg",
    categoryId: 2,
  },
  {
    id: 10,
    title: "House Salad",
    description:
      "Mixed greens with tomatoes, cucumbers, and choice of dressing.",
    price: "$5.99",
    image: "/images/10.jpg",
    categoryId: 2,
  },
  {
    id: 11,
    title: "Caprese Salad",
    description: "Tomatoes, fresh mozzarella, basil, and balsamic glaze.",
    price: "$7.99",
    image: "/images/11.jpg",
    categoryId: 2,
  },
  {
    id: 12,
    title: "Cobb Salad",
    description: "Mixed greens with chicken, bacon, avocado, and blue cheese.",
    price: "$12.99",
    image: "/images/12.jpg",
    categoryId: 2,
  },
  {
    id: 13,
    title: "Tuna Salad",
    description: "Fresh tuna with greens, onions, and vinaigrette.",
    price: "$11.99",
    image: "/images/13.jpg",
    categoryId: 2,
  },
  {
    id: 14,
    title: "Grilled Chicken Salad",
    description: "Grilled chicken served on a bed of fresh greens.",
    price: "$10.99",
    image: "/images/14.jpg",
    categoryId: 2,
  },
  {
    id: 15,
    title: "Spaghetti Bolognese",
    description: "Pasta topped with a rich meat sauce.",
    price: "$14.99",
    image: "/images/15.jpg",
    categoryId: 3,
  },
  {
    id: 16,
    title: "Chicken Parmesan",
    description: "Breaded chicken breast with marinara and mozzarella.",
    price: "$16.99",
    image: "/images/16.jpg",
    categoryId: 3,
  },
  {
    id: 17,
    title: "Grilled Salmon",
    description: "Perfectly grilled salmon with lemon butter.",
    price: "$19.99",
    image: "/images/17.jpg",
    categoryId: 3,
  },
  {
    id: 18,
    title: "Vegetable Stir Fry",
    description: "A medley of fresh vegetables stir-fried in a savory sauce.",
    price: "$13.99",
    image: "/images/18.jpg",
    categoryId: 3,
  },
  {
    id: 19,
    title: "Beef Tenderloin",
    description: "Juicy tenderloin served with mashed potatoes.",
    price: "$22.99",
    image: "/images/19.jpg",
    categoryId: 3,
  },
  {
    id: 20,
    title: "Lamb Chops",
    description: "Grilled lamb chops with rosemary sauce.",
    price: "$24.99",
    image: "/images/20.jpg",
    categoryId: 3,
  },
  {
    id: 21,
    title: "Chicken Alfredo",
    description: "Creamy pasta with grilled chicken and Alfredo sauce.",
    price: "$15.99",
    image: "/images/21.jpg",
    categoryId: 3,
  },
  {
    id: 22,
    title: "Cheesecake",
    description: "Rich and creamy cheesecake topped with strawberry sauce.",
    price: "$6.99",
    image: "/images/22.jpg",
    categoryId: 4,
  },
  {
    id: 23,
    title: "Tiramisu",
    description: "Classic Italian dessert with layers of coffee-soaked cake.",
    price: "$7.99",
    image: "/images/23.jpg",
    categoryId: 4,
  },
  {
    id: 24,
    title: "Chocolate Lava Cake",
    description: "Warm chocolate cake with a molten center.",
    price: "$8.99",
    image: "/images/24.jpg",
    categoryId: 4,
  },
  {
    id: 25,
    title: "Gelato",
    description: "Italian-style ice cream with a variety of flavors.",
    price: "$5.99",
    image: "/images/25.jpg",
    categoryId: 4,
  },
  {
    id: 26,
    title: "Apple Pie",
    description: "Classic apple pie with a buttery crust.",
    price: "$4.99",
    image: "/images/26.jpg",
    categoryId: 4,
  },
  {
    id: 27,
    title: "Crème Brûlée",
    description: "Creamy custard with a caramelized sugar top.",
    price: "$7.49",
    image: "/images/27.jpg",
    categoryId: 4,
  },
  {
    id: 28,
    title: "Panna Cotta",
    description: "Vanilla-flavored Italian dessert served with berry compote.",
    price: "$6.49",
    image: "/images/28.jpg",
    categoryId: 4,
  },
  {
    id: 29,
    title: "Coffee",
    description: "Freshly brewed coffee served hot.",
    price: "$2.99",
    image: "/images/29.jpg",
    categoryId: 5,
  },
  {
    id: 30,
    title: "Iced Tea",
    description: "Refreshing iced tea with lemon.",
    price: "$2.49",
    image: "/images/30.jpg",
    categoryId: 5,
  },
  {
    id: 31,
    title: "Lemonade",
    description: "Freshly squeezed lemonade.",
    price: "$3.49",
    image: "/images/31.jpg",
    categoryId: 5,
  },
  {
    id: 32,
    title: "Herbal Tea",
    description: "A soothing cup of herbal tea with calming flavors.",
    price: "$1.99",
    image: "/images/32.jpg",
    categoryId: 5,
  },
  {
    id: 33,
    title: "Milkshake",
    description: "Thick and creamy milkshake in vanilla or chocolate.",
    price: "$4.99",
    image: "/images/33.jpg",
    categoryId: 5,
  },
  {
    id: 34,
    title: "Juice",
    description: "Enjoy a selection of fresh-squeezed juices.",
    price: "$7.99",
    image: "/images/34.jpg",
    categoryId: 5,
  },
  {
    id: 35,
    title: "Sparkling Water",
    description: "Crisp and refreshing sparkling water with a hint of flavor.",
    price: "$5.49",
    image: "/images/35.jpg",
    categoryId: 5,
  },
];
